# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application
on:
  schedule:
    - cron: '40 15 * * *' #每日14点执行任务

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  work:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: szenius/set-timezone@v1.0 # 设置执行环境的时区
        with:
          timezoneLinux: "Asia/Shanghai"
      - uses: actions/setup-python@v4 # 使用python装配器
        with:
          python-version: '3.10' # 指定python版本
          # cache: 'poetry' # 设置缓存

      #- run: poetry install --without dev # 安装
      #- run: poetry run python .\main.py # 执行
      - run: python .\main.py
